name: progress_indicator_plus
description: "A Flutter package that provides customizable progress indicators with dynamic text color contrast."
version: 0.0.2
homepage: https://github.com/your-repo/progress_indicator_plus

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

